#include <stdio.h>
#include <stdlib.h>
#include <limits.h>

#define TMin INT_MIN
#define TMax INT_MAX

#include "btest.h"
#include "bits.h"

test_rec test_set[] = {
    {"absVal",
     (funct_t) absVal,
     (funct_t) test_absVal,
     1,
     "! ~ & ^ | + << >>",
     10,
     4,
     {{-TMax, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"addOK",
     (funct_t) addOK,
     (funct_t) test_addOK,
     2,
     "! ~ & ^ | + << >>",
     20,
     3,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"allEvenBits",
     (funct_t) allEvenBits,
     (funct_t) test_allEvenBits,
     1,
     "! ~ & ^ | + << >>",
     12,
     2,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"allOddBits",
     (funct_t) allOddBits,
     (funct_t) test_allOddBits,
     1,
     "! ~ & ^ | + << >>",
     12,
     2,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"anyEvenBit",
     (funct_t) anyEvenBit,
     (funct_t) test_anyEvenBit,
     1,
     "! ~ & ^ | + << >>",
     12,
     2,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"anyOddBit",
     (funct_t) anyOddBit,
     (funct_t) test_anyOddBit,
     1,
     "! ~ & ^ | + << >>",
     12,
     2,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"bang",
     (funct_t) bang,
     (funct_t) test_bang,
     1,
     "~ & ^ | + << >>",
     12,
     4,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"bitAnd",
     (funct_t) bitAnd,
     (funct_t) test_bitAnd,
     2,
     "| ~",
     8,
     1,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"bitCount",
     (funct_t) bitCount,
     (funct_t) test_bitCount,
     1,
     "! ~ & ^ | + << >>",
     40,
     4,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"bitMask",
     (funct_t) bitMask,
     (funct_t) test_bitMask,
     2,
     "! ~ & ^ | + << >>",
     16,
     3,
     {{0, 31}, {0, 31}, {TMin, TMax}}},

    {"bitMatch",
     (funct_t) bitMatch,
     (funct_t) test_bitMatch,
     2,
     "& | ~",
     14,
     1,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"bitNor",
     (funct_t) bitNor,
     (funct_t) test_bitNor,
     2,
     "& ~",
     8,
     1,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"bitOr",
     (funct_t) bitOr,
     (funct_t) test_bitOr,
     2,
     "& ~",
     8,
     1,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"bitParity",
     (funct_t) bitParity,
     (funct_t) test_bitParity,
     1,
     "! ~ & ^ | + << >>",
     20,
     4,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"bitReverse",
     (funct_t) bitReverse,
     (funct_t) test_bitReverse,
     1,
     "! ~ & ^ | + << >>",
     45,
     4,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"bitXor",
     (funct_t) bitXor,
     (funct_t) test_bitXor,
     2,
     "& ~",
     14,
     1,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"byteSwap",
     (funct_t) byteSwap,
     (funct_t) test_byteSwap,
     3,
     "! ~ & ^ | + << >>",
     25,
     2,
     {{TMin, TMax}, {0, 3}, {0, 3}}},

    {"conditional",
     (funct_t) conditional,
     (funct_t) test_conditional,
     3,
     "! ~ & ^ | << >>",
     16,
     3,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"copyLSB",
     (funct_t) copyLSB,
     (funct_t) test_copyLSB,
     1,
     "! ~ & ^ | + << >>",
     5,
     2,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"distinctNegation",
     (funct_t) distinctNegation,
     (funct_t) test_distinctNegation,
     1,
     "! ~ & ^ | +",
     5,
     2,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"dividePower2",
     (funct_t) dividePower2,
     (funct_t) test_dividePower2,
     2,
     "! ~ & ^ | + << >>",
     15,
     2,
     {{TMin, TMax}, {0, 30}, {TMin, TMax}}},

    {"evenBits",
     (funct_t) evenBits,
     (funct_t) test_evenBits,
     0,
     "! ~ & ^ | + << >>",
     8,
     1,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"ezThreeFourths",
     (funct_t) ezThreeFourths,
     (funct_t) test_ezThreeFourths,
     1,
     "! ~ & ^ | + << >>",
     12,
     3,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"fitsBits",
     (funct_t) fitsBits,
     (funct_t) test_fitsBits,
     2,
     "! ~ & ^ | + << >>",
     15,
     2,
     {{TMin, TMax}, {1, 32}, {TMin, TMax}}},

    {"fitsShort",
     (funct_t) fitsShort,
     (funct_t) test_fitsShort,
     1,
     "! ~ & ^ | + << >>",
     8,
     1,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"floatAbsVal",
     (funct_t) floatAbsVal,
     (funct_t) test_floatAbsVal,
     1,
     "$",
     10,
     2,
     {{1, 1}, {1, 1}, {1, 1}}},

    {"floatFloat2Int",
     (funct_t) floatFloat2Int,
     (funct_t) test_floatFloat2Int,
     1,
     "$",
     30,
     4,
     {{1, 1}, {1, 1}, {1, 1}}},

    {"floatInt2Float",
     (funct_t) floatInt2Float,
     (funct_t) test_floatInt2Float,
     1,
     "$",
     30,
     4,
     {{1, 1}, {1, 1}, {1, 1}}},

    {"floatIsEqual",
     (funct_t) floatIsEqual,
     (funct_t) test_floatIsEqual,
     2,
     "$",
     25,
     2,
     {{1, 1}, {1, 1}, {1, 1}}},

    {"floatIsLess",
     (funct_t) floatIsLess,
     (funct_t) test_floatIsLess,
     2,
     "$",
     30,
     3,
     {{1, 1}, {1, 1}, {1, 1}}},

    {"floatNegate",
     (funct_t) floatNegate,
     (funct_t) test_floatNegate,
     1,
     "$",
     10,
     2,
     {{1, 1}, {1, 1}, {1, 1}}},

    {"floatPower2",
     (funct_t) floatPower2,
     (funct_t) test_floatPower2,
     1,
     "$",
     30,
     4,
     {{1, 1}, {1, 1}, {1, 1}}},

    {"floatScale1d2",
     (funct_t) floatScale1d2,
     (funct_t) test_floatScale1d2,
     1,
     "$",
     30,
     4,
     {{1, 1}, {1, 1}, {1, 1}}},

    {"floatScale2",
     (funct_t) floatScale2,
     (funct_t) test_floatScale2,
     1,
     "$",
     30,
     4,
     {{1, 1}, {1, 1}, {1, 1}}},

    {"floatScale64",
     (funct_t) floatScale64,
     (funct_t) test_floatScale64,
     1,
     "$",
     35,
     4,
     {{1, 1}, {1, 1}, {1, 1}}},

    {"floatUnsigned2Float",
     (funct_t) floatUnsigned2Float,
     (funct_t) test_floatUnsigned2Float,
     1,
     "$",
     30,
     4,
     {{1, 1}, {1, 1}, {1, 1}}},

    {"getByte",
     (funct_t) getByte,
     (funct_t) test_getByte,
     2,
     "! ~ & ^ | + << >>",
     6,
     2,
     {{TMin, TMax}, {0, 3}, {TMin, TMax}}},

    {"greatestBitPos",
     (funct_t) greatestBitPos,
     (funct_t) test_greatestBitPos,
     1,
     "! ~ & ^ | + << >>",
     70,
     4,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"howManyBits",
     (funct_t) howManyBits,
     (funct_t) test_howManyBits,
     1,
     "! ~ & ^ | + << >>",
     90,
     4,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"implication",
     (funct_t) implication,
     (funct_t) test_implication,
     2,
     "! ~ ^ |",
     5,
     2,
     {{0, 1}, {0, 1}, {TMin, TMax}}},

    {"intLog2",
     (funct_t) intLog2,
     (funct_t) test_intLog2,
     1,
     "! ~ & ^ | + << >>",
     90,
     4,
     {{1, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"isAsciiDigit",
     (funct_t) isAsciiDigit,
     (funct_t) test_isAsciiDigit,
     1,
     "! ~ & ^ | + << >>",
     15,
     3,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"isEqual",
     (funct_t) isEqual,
     (funct_t) test_isEqual,
     2,
     "! ~ & ^ | + << >>",
     5,
     2,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"isGreater",
     (funct_t) isGreater,
     (funct_t) test_isGreater,
     2,
     "! ~ & ^ | + << >>",
     24,
     3,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"isLess",
     (funct_t) isLess,
     (funct_t) test_isLess,
     2,
     "! ~ & ^ | + << >>",
     24,
     3,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"isLessOrEqual",
     (funct_t) isLessOrEqual,
     (funct_t) test_isLessOrEqual,
     2,
     "! ~ & ^ | + << >>",
     24,
     3,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"isNegative",
     (funct_t) isNegative,
     (funct_t) test_isNegative,
     1,
     "! ~ & ^ | + << >>",
     6,
     2,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"isNonNegative",
     (funct_t) isNonNegative,
     (funct_t) test_isNonNegative,
     1,
     "! ~ & ^ | + << >>",
     6,
     2,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"isNonZero",
     (funct_t) isNonZero,
     (funct_t) test_isNonZero,
     1,
     "~ & ^ | + << >>",
     10,
     4,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"isNotEqual",
     (funct_t) isNotEqual,
     (funct_t) test_isNotEqual,
     2,
     "! ~ & ^ | + << >>",
     6,
     2,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"isPallindrome",
     (funct_t) isPallindrome,
     (funct_t) test_isPallindrome,
     1,
     "! ~ & ^ | + << >>",
     40,
     4,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"isPositive",
     (funct_t) isPositive,
     (funct_t) test_isPositive,
     1,
     "! ~ & ^ | + << >>",
     8,
     2,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"isPower2",
     (funct_t) isPower2,
     (funct_t) test_isPower2,
     1,
     "! ~ & ^ | + << >>",
     20,
     4,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"isTmax",
     (funct_t) isTmax,
     (funct_t) test_isTmax,
     1,
     "! ~ & ^ | +",
     10,
     1,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"isTmin",
     (funct_t) isTmin,
     (funct_t) test_isTmin,
     1,
     "! ~ & ^ | +",
     10,
     1,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"isZero",
     (funct_t) isZero,
     (funct_t) test_isZero,
     1,
     "! ~ & ^ | + << >>",
     2,
     1,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"leastBitPos",
     (funct_t) leastBitPos,
     (funct_t) test_leastBitPos,
     1,
     "! ~ & ^ | + << >>",
     6,
     2,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"leftBitCount",
     (funct_t) leftBitCount,
     (funct_t) test_leftBitCount,
     1,
     "! ~ & ^ | + << >>",
     40,
     4,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"logicalNeg",
     (funct_t) logicalNeg,
     (funct_t) test_logicalNeg,
     1,
     "~ & ^ | + << >>",
     12,
     4,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"logicalShift",
     (funct_t) logicalShift,
     (funct_t) test_logicalShift,
     2,
     "! ~ & ^ | + << >>",
     20,
     3,
     {{TMin, TMax}, {0, 31}, {TMin, TMax}}},

    {"minusOne",
     (funct_t) minusOne,
     (funct_t) test_minusOne,
     0,
     "! ~ & ^ | + << >>",
     2,
     1,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"multFiveEighths",
     (funct_t) multFiveEighths,
     (funct_t) test_multFiveEighths,
     1,
     "! ~ & ^ | + << >>",
     12,
     3,
     {{-(1 << 28) - 1, (1 << 28) - 1}, {TMin, TMax}, {TMin, TMax}}},

    {"negate",
     (funct_t) negate,
     (funct_t) test_negate,
     1,
     "! ~ & ^ | + << >>",
     5,
     2,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"oddBits",
     (funct_t) oddBits,
     (funct_t) test_oddBits,
     0,
     "! ~ & ^ | + << >>",
     8,
     2,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"remainderPower2",
     (funct_t) remainderPower2,
     (funct_t) test_remainderPower2,
     2,
     "! ~ & ^ | + << >>",
     20,
     3,
     {{TMin, TMax}, {0, 30}, {TMin, TMax}}},

    {"replaceByte",
     (funct_t) replaceByte,
     (funct_t) test_replaceByte,
     3,
     "! ~ & ^ | + << >>",
     10,
     3,
     {{TMin, TMax}, {0, 3}, {0, 255}}},

    {"rotateLeft",
     (funct_t) rotateLeft,
     (funct_t) test_rotateLeft,
     2,
     "! ~ & ^ | + << >>",
     25,
     3,
     {{TMin, TMax}, {0, 31}, {TMin, TMax}}},

    {"rotateRight",
     (funct_t) rotateRight,
     (funct_t) test_rotateRight,
     2,
     "! ~ & ^ | + << >>",
     25,
     3,
     {{TMin, TMax}, {0, 31}, {TMin, TMax}}},

    {"satAdd",
     (funct_t) satAdd,
     (funct_t) test_satAdd,
     2,
     "! ~ & ^ | + << >>",
     30,
     4,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"satMul2",
     (funct_t) satMul2,
     (funct_t) test_satMul2,
     1,
     "~ & ^ | + << >>",
     20,
     3,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"satMul3",
     (funct_t) satMul3,
     (funct_t) test_satMul3,
     1,
     "~ & ^ | + << >>",
     25,
     3,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"sign",
     (funct_t) sign,
     (funct_t) test_sign,
     1,
     "! ~ & ^ | + << >>",
     10,
     2,
     {{-TMax, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"signMag2TwosComp",
     (funct_t) signMag2TwosComp,
     (funct_t) test_signMag2TwosComp,
     1,
     "! ~ & ^ | + << >>",
     15,
     4,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"specialBits",
     (funct_t) specialBits,
     (funct_t) test_specialBits,
     0,
     "! ~ & ^ | + << >>",
     3,
     1,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"subtractionOK",
     (funct_t) subtractionOK,
     (funct_t) test_subtractionOK,
     2,
     "! ~ & ^ | + << >>",
     20,
     3,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"thirdBits",
     (funct_t) thirdBits,
     (funct_t) test_thirdBits,
     0,
     "! ~ & ^ | + << >>",
     8,
     1,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"tmax",
     (funct_t) tmax,
     (funct_t) test_tmax,
     0,
     "! ~ & ^ | + << >>",
     4,
     1,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"tmin",
     (funct_t) tmin,
     (funct_t) test_tmin,
     0,
     "! ~ & ^ | + << >>",
     4,
     1,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"trueFiveEighths",
     (funct_t) trueFiveEighths,
     (funct_t) test_trueFiveEighths,
     1,
     "! ~ & ^ | + << >>",
     25,
     4,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"trueThreeFourths",
     (funct_t) trueThreeFourths,
     (funct_t) test_trueThreeFourths,
     1,
     "! ~ & ^ | + << >>",
     20,
     4,
     {{TMin, TMax}, {TMin, TMax}, {TMin, TMax}}},

    {"twosComp2SignMag",
     (funct_t) twosComp2SignMag,
     (funct_t) test_twosComp2SignMag,
     1,
     "! ~ & ^ | + << >>",
     15,
     4,
     {{TMin + 1, TMax}, {TMin + 1, TMax}, {TMin + 1, TMax}}},

    {"upperBits",
     (funct_t) upperBits,
     (funct_t) test_upperBits,
     1,
     "! ~ & ^ | + << >>",
     10,
     1,
     {{0, 32}, {TMin, TMax}, {TMin, TMax}}},

    {"", NULL, NULL, 0, "", 0, 0, {{0, 0}, {0, 0}, {0, 0}}}};
